services:
    laravel.test:
        build:
            context: './vendor/laravel/sail/runtimes/8.3'
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: 'sail-8.3/app'
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            # Alteração da porta do Laravel para evitar conflito com outras portas
            - '${APP_PORT:-8080}:80'   # Mudança da porta 80 para 8080 para evitar conflito
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
            IGNITION_LOCAL_SITES_PATH: '${PWD}'
        volumes:
            - '.:/var/www/html'
        networks:
            - sail
        depends_on:
            - mysql
            - redis
            - meilisearch
            - mailpit
            - selenium

    mysql:
        image: 'mysql/mysql-server:8.0'
        # Alteração da porta do MySQL para evitar conflito com outra instância MySQL no sistema
        ports:
            - '${FORWARD_DB_PORT:-3307}:3306'  # Mudança da porta 3306 para 3307 para evitar conflito
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - 'sail-mysql:/var/lib/mysql'
            - './vendor/laravel/sail/database/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
        networks:
            - sail
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - '-p${DB_PASSWORD}'
            retries: 3
            timeout: 5s

    redis:
        image: 'redis:alpine'
        # Alteração da porta do Redis para evitar conflito
        ports:
            - '${FORWARD_REDIS_PORT:-6380}:6379'  # Mudança da porta 6379 para 6380
        volumes:
            - 'sail-redis:/data'
        networks:
            - sail
        healthcheck:
            test:
                - CMD
                - redis-cli
                - ping
            retries: 3
            timeout: 5s

    meilisearch:
        image: 'getmeili/meilisearch:latest'
        # Alteração da porta do MeiliSearch para evitar conflito
        ports:
            - '${FORWARD_MEILISEARCH_PORT:-7701}:7700'  # Mudança da porta 7700 para 7701
        environment:
            MEILI_NO_ANALYTICS: '${MEILISEARCH_NO_ANALYTICS:-false}'
        volumes:
            - 'sail-meilisearch:/meili_data'
        networks:
            - sail
        healthcheck:
            test:
                - CMD
                - wget
                - '--no-verbose'
                - '--spider'
                - 'http://127.0.0.1:7700/health'
            retries: 3
            timeout: 5s

    mailpit:
        image: 'axllent/mailpit:latest'
        # Alteração da porta do Mailpit para evitar conflito
        ports:
            - '${FORWARD_MAILPIT_PORT:-1026}:1025'  # Mudança da porta 1025 para 1026
            - '${FORWARD_MAILPIT_DASHBOARD_PORT:-8026}:8025'  # Mudança da porta 8025 para 8026
        networks:
            - sail

    selenium:
        image: selenium/standalone-chromium
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        volumes:
            - '/dev/shm:/dev/shm'
        networks:
            - sail

networks:
    sail:
        driver: bridge

volumes:
    sail-mysql:
        driver: local
    sail-redis:
        driver: local
    sail-meilisearch:
        driver: local
